### ISSUE TITLE
pmin and pmax possible equality

### ISSUE THREAD

**Issue by dnav** [core-wg/dynlink#25]
Hi,

OMA LwM2M is using Minimum Period (pmin) and Maximum Period (pmax) attributes.

The DynLink draft has this requirement:

> The maximum period MUST be greater than zero and MUST be greater than the minimum period parameter (if present)

In its version 1.0, LwM2M had a different version of this requirement in the form:

>  The maximum period parameter MUST be not smaller than the minimum period parameter.

Thus having pmax equal to pmin was allowed.

In LwM2M 1.1 we aligned this requirement with the DynLink one, making pmin equal to pmax forbidden.

However, it was [brought to our attention](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/495) that having pmin equal pmax is a valid use case if the client wants the notification to be sent exactly every N seconds.

Is there a strong opinion on forbidding pmax to be equal to pmin, or are people open to changing the Dynlink requirement ?

> The maximum period MUST be greater than zero and MUST be greater than **or equal to** the minimum period parameter (if present)

Regards

**Comment by bsilverajan** [comment]
@dnav After the discussion at IETF 109, I think we can agree that there are no strong opinions against allowing pmax to be greater than or equal to pmin in the draft.

However in order to avoid any ambiguity in interpretation, do we want reflect the discussion so far, so that the draft has pmax == pmin, specifically for this use case, ie when this condition is met, then the CoAP server sends (is it a MUST/SHOULD/MAY?) the resource representation every N seconds?

Also how does the client then cancel this request?

**Comment by bsilverajan** [comment]
Closing this issue, with the draft allowing pmax to have equality to pmin
