### ISSUE TITLE
Merging additional CoAP Binding and Observe attributes from draft-groves-core-obsattr-00

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/dynlink#6]
The authors have discussed merging some of the binding and observe attributes, namely from Sections 4.2 to 4.4 from draft-groves-core-obsattr-00

**Comment by Julian-ZJT** [comment]
As we discussed, we propose to add a new attribute "band" to make the attribute "gt", "lt" and "st" behave as "band" attributes "bmn", "bmx" and "bst" as specified in  draft-groves-core-obsattr-00.

4.2. Notification Band Minimum (bmn)
This attribute defines the lower bound for the notification band.
State synchronization occurs when the resource value is equal to or
above the notification band minimum. This attribute is optional. If
not present there is no minimum value for the band. If present bmn
must be less than bmx if it is also present otherwise the receiver
MUST return a CoAP error code 4.00 "Bad Request" (or equivalent).

4.3. Notification Band Maximum (bmx)
This attribute defines the upper bound for the notification band.
State synchronization occurs when the resource value is equal to or
less than the notification band maximum. This attribute is optional.
If not present there is no maximum value for the band. If present
bmx must be more than bmn if it is also present, otherwise the
receiver MUST return a CoAP error code 4.00 "Bad Request" (or
equivalent).

4.4. Band Step (bst)
Like change step (st) this attribute indicates how much the value of
a resource SHOULD change before triggering a state synchronization.
The difference however is that the values used for the band step
calculation are based on a constant step rather than being based on
the synchronized value.
The current resource value or the initialization value (if provided)
is used a seed to determine the band thresholds.
For example: Given a bst=10 and an initialization value=25. This
defines a series of band step thresholds: i.e. ...,
(5,15],(15,25],(25,35], ...
When the resource value enters a new band step by exceeding the
minimum threshold value and being less than or equal to the maximum
threshold value for a band step then synchronisation occurs.
A new synchronization occurs whenever the value enters a new band
step. If the value jumps across band steps e.g. from 13 to 27 only
one synchronisation occurs.
The band step MUST be greater than zero otherwise the server MUST
return a CoAP error code 4.00 "Bad Request" (or equivalent).
Change step (st) and band step (bst) MUST NOT occur together in the
same query.

**Comment by bsilverajan** [comment]
There are 2 points to clarify:

1.  For the band step behaviour this is the current text:
> For example: Given a bst=10 and an initialization value=25. This
defines a series of band step thresholds..

Is the "iv" attribute therefore also required?

2. Could you clarify that the "band" attribute does not need to contain any value?

**Comment by Julian-ZJT** [comment]
1. My answer is NO to the 'iv' attribute for compatibility. Because there's no corresponding attribute in current draft [dynlink].

2. My view is that the attribute 'band' is a boolean. Which is OPTIONAL, 
if it is NOT presented or presented with the value N, then the gt\lt\st are processed as they are now specified in [Dynlink];
if it is presented with the value Y, then the gt\lt\st are processed as described in this thread.

**Comment by bsilverajan** [comment]
@Julian-ZJT I've now amended draft -05 to include these points. Does the current wording in the draft provide sufficient clarity on the use of "band"?

**Comment by bsilverajan** [comment]
This has now been resolved
