### ISSUE TITLE
gt and lt interactions

### ISSUE THREAD

**Issue by bsilverajan** [core-wg/dynlink#9]
Current text in Section 3.3.8, on Attribute Interactions:

> If gt and lt are included gt MUST be greater than lt otherwise an error CoAP error code 4.00 “Bad Request” (or equivalent) MUST be returned.

Would there be valid cases where gt would be less than lt?

**Comment by cabo** [comment]
On Jun 21, 2018, at 15:40, Bill Silverajan <notifications@github.com> wrote:
> 
> Current text in Section 3.3.8, on Attribute Interactions:
> 
> If gt and lt are included gt MUST be greater than lt otherwise an error CoAP error code 4.00 “Bad Request” (or equivalent) MUST be returned.
> 
> Would there be valid cases where gt would be less than lt?

We had discussed this in a way that implies gt could be less than lt to have a band of values that cause updates.
I.e., “only tell me about temperatures that fall in the critical region between 280 and 350 K” would be gt=280&lt=350
The text doesn’t quite agree with a usage where you want notifications of out-of-band values (e.g., gt=350&lt=280) as it seems to imply a disjunction that will never be true; this will need to be fixed.
All this also needs to be aligned with “band”.

There are many ways to design this; the problem is that some of this code is already out there and we don’t want to break it too hard.

Grüße, Carsten

**Comment by bsilverajan** [comment]
Closing after discussions with the authors: Removal of the text
